"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, MessageSquare, RefreshCw } from "lucide-react";
import { supabase } from "@/lib/supabase/client";
type Msg={id:string;body:string;sender:string|null;recipient:string|null;received_at:string;rental_id:string};
export default function Inbox(){const [messages,setMessages]=useState<Msg[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
async function load(){setLoading(true);setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/auth";return;}const {data,error}=await supabase.from("messages").select("id,body,sender,recipient,received_at,rental_id").order("received_at",{ascending:false}).limit(100);if(error)setError(error.message);setMessages((data as Msg[])||[]);setLoading(false)}
useEffect(()=>{load()},[]);return <main className="min-h-screen"><div className="mx-auto max-w-4xl px-5 py-10"><Link href="/dashboard" className="flex items-center gap-2 text-sm text-green-400"><ArrowLeft size={15}/> Dashboard</Link><div className="mt-6 flex items-center justify-between"><div><h1 className="text-3xl font-black">Message inbox</h1><p className="mt-2 text-slate-400">Messages delivered to numbers you control.</p></div><button onClick={load} className="rounded-xl border border-slate-700 p-3" title="Refresh"><RefreshCw size={18}/></button></div>{error&&<p className="mt-5 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}<div className="mt-7 space-y-3">{loading?<p className="text-slate-400">Loading messages...</p>:messages.length===0?<div className="card p-10 text-center"><MessageSquare className="mx-auto text-green-400"/><h2 className="mt-3 font-bold">No messages yet</h2><p className="mt-2 text-sm text-slate-400">Incoming messages will appear here when your provider delivers them.</p></div>:messages.map(m=><article key={m.id} className="card p-5"><div className="flex justify-between gap-4"><span className="text-sm font-semibold">{m.sender||"Unknown sender"}</span><time className="text-xs text-slate-500">{new Date(m.received_at).toLocaleString()}</time></div><p className="mt-3 whitespace-pre-wrap leading-6 text-slate-200">{m.body}</p>{m.recipient&&<p className="mt-3 text-xs text-slate-500">To {m.recipient}</p>}</article>)}</div></div></main>}
