"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase/client";

type Country={id:string;name:string;iso_code:string;dial_code:string};
type NumberItem={id:string;phone_number:string;monthly_price:number;currency:string;countries:Country|null};

export default function NumbersPage(){const [numbers,setNumbers]=useState<NumberItem[]>([]);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");useEffect(()=>{(async()=>{const {data}=await supabase.from("virtual_numbers").select("id,phone_number,monthly_price,currency,countries(id,name,iso_code,dial_code)").eq("status","available").limit(50);setNumbers((data as NumberItem[])||[]);setLoading(false)})()},[]);return <main className="min-h-screen"><div className="mx-auto max-w-5xl px-5 py-10"><Link href="/dashboard" className="text-sm text-green-400">← Dashboard</Link><h1 className="mt-5 text-3xl font-black">Available numbers</h1><p className="mt-2 max-w-2xl text-slate-400">Inventory is supplied by authorized providers. A payment and provisioning flow will be enabled after a provider is connected.</p>{notice&&<p className="mt-5 rounded-xl border border-green-400/20 bg-green-400/10 p-3 text-sm text-green-200">{notice}</p>}<div className="mt-8 grid gap-4 md:grid-cols-2">{loading?<p className="text-slate-400">Loading availability...</p>:numbers.length===0?<div className="card p-8 md:col-span-2"><h2 className="font-bold">No inventory has been added yet</h2><p className="mt-2 text-sm text-slate-400">Once an authorized number provider is connected, available inventory will appear here.</p></div>:numbers.map(n=><div key={n.id} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">{n.countries?.name||"International"}</p><h2 className="mt-1 font-mono text-xl font-bold">{n.phone_number}</h2></div><span className="text-sm font-bold text-green-400">{n.currency} {n.monthly_price}/mo</span></div><button onClick={()=>setNotice("Number selection is ready. Checkout will be enabled when the payment and provider provisioning integration is connected.")} className="mt-5 w-full rounded-xl border border-slate-700 py-2.5 font-semibold hover:border-green-400">Select number</button></div>)}</div></div></main>}
