"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "@/lib/supabase/client";
import { LogOut, Phone, MessageSquare, CreditCard, Plus } from "lucide-react";

type Rental = { id: string; status: string; expires_at: string | null; virtual_numbers: { phone_number: string; currency: string; monthly_price: number } | null };

export default function Dashboard() {
  const [email, setEmail] = useState(""); const [rentals, setRentals] = useState<Rental[]>([]); const [loading, setLoading] = useState(true);
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href="/auth";return;} setEmail(user.email||""); const {data}=await supabase.from("rentals").select("id,status,expires_at,virtual_numbers(phone_number,currency,monthly_price)").order("created_at",{ascending:false}); setRentals((data as Rental[])||[]); setLoading(false);})()},[]);
  async function logout(){await supabase.auth.signOut();window.location.href="/";}
  return <main className="min-h-screen"><header className="border-b border-slate-800"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/" className="text-xl font-black">Number<span className="text-green-400">ly</span></Link><div className="flex items-center gap-3 text-sm text-slate-400"><span className="hidden sm:block">{email}</span><button onClick={logout} className="rounded-lg border border-slate-700 p-2"><LogOut size={16}/></button></div></div></header><div className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-green-400">Dashboard</p><h1 className="mt-1 text-3xl font-black">Your virtual numbers</h1></div><Link href="/numbers" className="gradient flex items-center gap-2 rounded-xl px-4 py-3 font-bold text-slate-950"><Plus size={18}/> Get a number</Link></div><div className="mt-8 grid gap-4 md:grid-cols-3"><Stat icon={<Phone/>} label="Active numbers" value={loading?"—":String(rentals.filter(r=>r.status==="active").length)}/><Stat icon={<MessageSquare/>} label="Messages" value="Coming soon"/><Stat icon={<CreditCard/>} label="Payments" value="Secure history"/></div><section className="mt-8"><h2 className="text-lg font-bold">My numbers</h2>{loading?<p className="mt-4 text-slate-400">Loading your numbers...</p>:rentals.length===0?<div className="card mt-4 p-8 text-center"><Phone className="mx-auto text-green-400"/><h3 className="mt-3 font-bold">No virtual numbers yet</h3><p className="mt-2 text-sm text-slate-400">Browse supported countries and request a number when inventory is available.</p><Link href="/numbers" className="mt-5 inline-block text-sm font-bold text-green-400">Browse numbers →</Link></div>:<div className="mt-4 grid gap-4 md:grid-cols-2">{rentals.map(r=><div key={r.id} className="card p-5"><div className="flex justify-between"><span className="font-mono text-lg">{r.virtual_numbers?.phone_number}</span><span className="rounded-full bg-green-400/10 px-2 py-1 text-xs text-green-300">{r.status}</span></div><p className="mt-3 text-sm text-slate-400">Expires: {r.expires_at?new Date(r.expires_at).toLocaleDateString():"Not set"}</p></div>)}</div>}</section></div></main>;
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="card p-5"><div className="flex items-center gap-3 text-green-400">{icon}<span className="text-sm text-slate-400">{label}</span></div><p className="mt-4 text-xl font-bold">{value}</p></div>}
